# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 4.0.5
_src_path: gh:epics-containers/services-template-helm
cluster_name: dev-hive
cluster_namespace: dev-hive
cluster_type: ''
description: dev-hive IOC Instances and Services
git_platform: github.com
github_org: buzz-metrics
ioc_group: dev-hive
location: dev-hive
logging_url: ''
repo_uri: https://github.com/buzz-metrics/dev-hive-services
